name: Publish the WebHID demo to pages

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish-demo:
    name: Publish demo to Github Pages
    runs-on: ubuntu-latest
    continue-on-error: false
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Use Node.js 22
        uses: actions/setup-node@v6
        with:
          node-version: 22
      - name: Prepare Environment
        run: |
          corepack enable
          yarn install --immutable
          yarn build
        env:
          CI: true
      - name: Publish
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/webhid-demo/dist
